spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://ep-soft-recipe-a189x52v-pooler.ap-southeast-1.aws.neon.tech/auth?sslmode=require&channel_binding=require
    username: learning_postgres_owner
    password: t8qELP1OjCFp
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
#        ddl-auto: validate
        ddl-auto: update
#        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          globally_quoted_identifiers: true
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
      mode: always
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: debug
server:
  port: 4005
jwt:
  secret: qK1a7vK1p5Q9v8kFJw1Xz5w8a3kR2jZkq8l2vQx7y5E=