### POST request to create patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
  "password": "Chaitanya Sharma",
  "email": "cfsddf3@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "2001-03-27",
  "registeredDate": "2021-03-27"
}
###