### POST request to create patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Chaitanya Sharma",
  "email": "c3@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "2001-03-27",
  "registeredDate": "2021-03-27"
}
###