spring:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  application:
    name: patient-service
  datasource:
#    url: jdbc:postgresql://ep-soft-recipe-a189x52v-pooler.ap-southeast-1.aws.neon.tech/patient-management?sslmode=require
#    username: learning_postgres_owner
#    password: t8qELP1OjCFp
    driver-class-name: org.postgresql.Driver
  jpa:
#    hibernate:
#      ddl-auto: validate
    #      ddl-auto: create-drop
    #      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 4000

logging:
  level:
    root: Info
kafka:
  producer:
    cron:
      expression: 0/10 * * * * *

