### GET request to validate
GET http://localhost:4004/auth/validate
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlckB0ZXN0LmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTgyNTAzOCwiZXhwIjoxNzUxODYxMDM4fQ.mnokCfoEb4ierbQWM804Hl8iWWVPovDiYvjmxRtA-bs
###

